version: "3"

networks:
  gitea:
    external: false
  frontend:
    name: frontend
    external: true

services:
  # Gitea
  server:
    image: docker.gitea.com/gitea:1.25.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    networks:
      - frontend
      - gitea
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.immich-server.rule=Host(`gitea.lucasmasse.net`)"
        - "traefik.http.routers.immich-server.entrypoints=websecure"
        - "traefik.http.routers.immich-server.tls=true"
        - "traefik.http.routers.immich-server.tls.certresolver=letencrypt"
        - "traefik.http.services.immich-server.loadbalancer.server.port=3000"
    restart: always
    volumes:
      - /data/portainer/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  # BDD Gitea
  db:
    image: docker.io/library/mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
     - /data/portainer/gitea/mysql:/var/lib/mysql

  # Runner
  runner:
    image: docker.io/gitea/act_runner:nightly
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "https://gitea.lucasmasse.net"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "${RUNNER_NAME}"
      GITEA_RUNNER_LABELS: "${RUNNER_LABELS}"
    networks:
      - frontend
      - gitea
    volumes:
      - /data/portainer/gitea/runner/config.yaml:/config.yaml
      - /data/portainer/gitea/runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock